version: '3'

services:
  etcd:
    container_name: etcds
    image: docker.io/bitnami/etcd:3
    ports:
      - 2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local